image: node:12
pages:
  stage: deploy
  script:
  - npm install
  - npm run-script build
  environment:
    name: staging
    url: https://dev.suuk.gitlab.io/data-visualization-project/
  artifacts:
    paths:
    - public
  only:
  - master
